### ISSUE TITLE
Eurostar font issue on firefox mobile

### ISSUE THREAD

**Issue by afonso360** [zegreatclan/SimHub#302]
Hi,

I've been having issues with the Eurostar font on firefox mobile. This dashboard works fine on the desktop version of firefox.

In the `FontFaces.css` file this is the entry for the Eurostar font:
```css
@font-face {
    font-family: "Eurostar Black Extended";
    src: url('/Fonts/eurostarblackextended.ttf');   
}
```
Desktop firefox(63.0.3) correctly matches the `font-family: "Eurostar";` to that font-face. 
However, in the tablet I have firefox(63.0.2) and it can't match that font family.

I've tried to change the font family manually to "Eurostar Black Extended" in the WebIDE Inspector and the tablet displays the correct font.

Is there any easy solution to fix this?

I can't use chrome, because there is a weird refresh issue. But on chrome it works fine.
